### ISSUE TITLE
ep2-us4 🖥️ naming conventions and taxonomy

### ISSUE THREAD

**Issue by StephMode** [levinthiel/KoroKoro#11]
## Outline

We need standards and conventions for
- how we refer to parts of the game/app
- how we want to name components
- how we want to name functions

This will help us to maintain clean code.

We need a clear terminology.
This will enable concise communication on all channels.

## Description

wireframe

## Acceptance Criteria

- There is a single source of truth for terminology and naming conventions.
- The source contains at least definitions for evertything we developed so far.
- The terminology and naming conventions is dicussed within the team before initliazation.

## Tasks

- [x] Prepare draft as basis for discussion on Miro/shared Document
- [x] Research platform for single source of truth
- [x] Create single source of truth
- [x] discuss reccomendations for glossary and naming in team
- [x] create `.md` file containing glossary and naming convention
- [x] improve naming of pages and components as discussed

**Comment by StephMode** [comment]
A more appropriate term for this might be "glossary" as part of a larger:
- wiki
- documentation
- game design document

**Comment by StephMode** [comment]
For the time being, we decided to have a simple `.md` in the project's `root` directory which contains all the definitions we have set and agreed on so far.

The `.md` will be migrated to another medium at a later stage.

**Comment by StephMode** [comment]
Also, this US will also contain first actual improvementes of the code base itself based on the glossary and conventions discussed in the team
