### ISSUE TITLE
ep2-us5 🎨 texts for opening sequence

### ISSUE THREAD

**Issue by StephMode** [levinthiel/KoroKoro#12]
## Value Proposition

**As a player**

**I want**  to have engaging texts in the opening sequence

**So  that** I can enjoy a complete opening sequence.

## Description

wireframe

## Acceptance Criteria

- Sentences are brief independent clauses or elliptic clauses. 
- The style invokes an atmosphere of wonder.
- dataset adheres to naming conventions and best practises

## Tasks

- [x] refine first drafts of intro sequence texts on Miro board
- [x] update `scenes` dataset with updated texts
- [x] improve naming of properties in data set objects

**Comment by StephMode** [comment]
On task "improve naming of properties …"

While revisiting the `scenes` dataset I noticed potential for improvement in the data set:

```JS
export const scenes = [
    {
        id:1,
        name:"scene1",
        textpart:"In the vast expanse of the universe, there exists a cluster of shimmering nebulas", // should be textPart
        imagesource: "/space1-600.png", // should be imageSource
// ...
```

We should definitely ensure clean code by adjusting the key-naming.

@levinthiel : I didn't notice it myself while working on the last feature and also not while doing the code review. So I will include it in the work for this US. Let's always try to stick to these general practises.

**Comment by StephMode** [comment]
> On task "improve naming of properties …"
> 
> While revisiting the `scenes` dataset I noticed potential for improvement in the data set:
> 
> export const scenes = [
>     {
>         id:1,
>         name:"scene1",
>         textpart:"In the vast expanse of the universe, there exists a cluster of shimmering nebulas", // should be textPart
>         imagesource: "/space1-600.png", // should be imageSource
> // ...
> 
> We should definitely ensure clean code by adjusting the key-naming.
> 
> [@levinthiel](https://github.com/levinthiel) : I didn't notice it myself while working on the last feature and also not while doing the code review. So I will include it in the work for this US. Let's always try to stick to these general practises.

@levinthiel 

Also we could think of the follwing adjustments:
- `WE SHOULD CHANGE THAT` consecutive numbering of the `name` properties instead of "scene1" twice and the same with "scene2" and so on.
- `JUST AN IDEA` the images could be renamed like "openingSceneImage1" and so on. This could make it more simple to change the images in the dedicated page based on props and template literals by just changig a `number` value instead of a string.
