### ISSUE TITLE
ep2-us8 🖥️ button on Title screen

### ISSUE THREAD

**Issue by StephMode** [levinthiel/KoroKoro#14]
## Value Proposition/Outline

**As a player**

**I want** to have a keyboard-controlled cursor on the start screen

**So  that** I can navigate the start screen like in a 16-bit-era game.

## Description

wireframe

## Acceptance Criteria

- There is a cursor element on the start screen.
- The cursor element on the start screen can be controlled using the keyboard.

## Tasks

- [x] create feature branch
- [x] develop cursor to toggle button on start screen
- [x] remove splash screen 2
- [x] add KoroKoro logo on title screen
