### ISSUE TITLE
ep2-us7 🖥️ opening cinematic sequence

### ISSUE THREAD

**Issue by StephMode** [levinthiel/KoroKoro#15]
## Value Proposition/Outline

**As a player**

**I want to** have a beautiful opening sequence with text and images

**So that I** can immerse myself into the game.

## Description

wireframe

## Acceptance Criteria

- There's a sequence with text and images.
- The sequence is togglebale.

## Tasks

- [x] create feature branch
- [x] develop opening cinematic sequence (data set, mapping, sequencing)
- [x] develop functional text toggler for opening cinematic sequence
