### ISSUE TITLE
ep1-us4  🖥️ develop mock up display

### ISSUE THREAD

**Issue by StephMode** [levinthiel/KoroKoro#4]
# Goal

We want to have a very basic mock-up of the future UI which will resemble the origninal "tamagotchi" handheld device.

# Guidelines

- `body` (dark color)
- `wrapper` ( center center viewport e.g. 1000x1000)
- `Egg`  (center center)
- `Screen` (fixed inside egg)

Additionally, we can also include dummy elements for the `Button`s

# Tasks
 

- [x] create a branch `feature-ep1-us4-{name}-mock-up-display`
- [x] delete basic nextJS styling and content
- [x] cerate mock up
- [x] play around with the mock-up to determine optimal `Screen` size
- [x] modify styling to ensure baseline reponsiveness: context: https://github.com/levinthiel/KoroKoro/commit/e663226c4b0078d14d92d5fbc38698d0413cec24
- [x] make seperate pages for `KoroKoroDex` for player UI and `MainPage` for intro**
- [ ] investigate `TypeError`, context: https://github.com/levinthiel/KoroKoro/commit/6c631835a84a75b158df9cb7f0c5030522cbf29a

**Comment by StephMode** [comment]
reagarding:

modify styling to ensure baseline reponsiveness: context: https://github.com/levinthiel/KoroKoro/commit/e663226c4b0078d14d92d5fbc38698d0413cec24

We agreed that the styling as layed out in https://github.com/levinthiel/KoroKoro/commit/e663226c4b0078d14d92d5fbc38698d0413cec24 is fine for the time being and we don't need to refine it atm.

**Comment by StephMode** [comment]
On task:

investigate TypeError, context: https://github.com/levinthiel/KoroKoro/commit/6c631835a84a75b158df9cb7f0c5030522cbf29a

'useclient' actually has nothing to do with StyledComponents. It's needed because we are using app router and thus we'll need it in every client-side page going forward.

In Next.js projects with app router `'useclient'` is used to sepreate concerns between client-side and server side components.

Thus, to resolve this task I just deleted the comments.

**Comment by StephMode** [comment]
On this TODO in the code:

```JS
import styles from "./page.module.css";
// TODO: check if this is still needed and delete if possible
```

Not needed so I deleted it.
