### ISSUE TITLE
animation sequence not mounting properly

### ISSUE THREAD

**Issue by StephMode** [levinthiel/KoroKoro#6]
# Description

## Context

In PR https://github.com/levinthiel/KoroKoro/pull/5 for US https://github.com/levinthiel/KoroKoro/issues/4 we developed a sequence of animations which display the studio-logo, the logo of the game and ending in a simple "start menu" for dev purposes.

## Problem

In production (vercel), the animation sequence doesn't start properly upon mounting. 
It only starts if the user goes through the following flow:
1. click on one of the links of `IntroScreen3`
2. On one of the pages (`game UI` or `opening cimematic` page)
3. Click on the `back to  home`
4. Animation sequence plays on the `Home` page

We need to fix this. The animation needs to be also played upon mounting.

https://korokoro.vercel.app/

# Tasks

- [ ] create branch `bugfix-`
- [x] investigate animation sequence not playing as intended in production
- [x] improve logic if feasible

**Comment by StephMode** [comment]
Refer to NextJS setup by neuefische for capstone as reference

**Comment by StephMode** [comment]
@levinthiel I solved this issue in https://github.com/levinthiel/KoroKoro/commit/7b16b15696a08662a09d4db59460db07fa4da640. 

As a matter of fact, I made the changes and commits directly on `main` without creating a feature-branch. I would usually refrain from this approach as we agreed to have a feature-based-branching-strategy. 

However, due to the fact that this bug/undesired rendering is only really visible on production (on our dev servers the splash screen sequence always ran properly"), I had to develop this trunk-based because the changes could only be checked on production.

With the additional NextJS confgurations being made, our mounting sequence runs properly now 😎

For further technical details and references please refer to the referenced commit.
