### ISSUE TITLE
ep2-us1 🖥️-refine layout for opening cinematic page

### ISSUE THREAD

**Issue by StephMode** [levinthiel/KoroKoro#7]
# Goal

We want to have a very basic mock-up of the future UI which will resemble the origninal "tamagotchi" handheld device.

# Guidelines

- elements on the `OpeningCinematicPage` are responsive to mobile viewport, iPad, desktop
- there is placeholder text and image

# Tasks
 
- [x] create a branch `feature-ep2-us1-{name}-refine-opening-page`
- [x] make layout for `OpeningCinematicPage` responsive
- [x] implement hard-coded text and image
